### ISSUE TITLE
[Question] Why does passing a float value is not recommended?

### ISSUE THREAD

**Issue by ajcastro** [rtlopez/decimal#2]
![image](https://cloud.githubusercontent.com/assets/4918318/23645928/936c47ec-0349-11e7-92b2-6b698f20960e.png)

If that so, maybe we can cast it into string, so that it will be just fine :).

**Comment by rtlopez** [comment]
Passing a float is not recommended because float is only an approximation and you still may experience some rounding issues. In practice it is converted into string, see class DecimalBCMath.php in line 112. Technically it is possible only because some other apis or libraries return floats, but you have to bear in mind that strange behavior is possible.

Here is a small sample:
```php
<?php
require 'vendor/autoload.php';

use RtLopez\Decimal;

$f1 =  123456.6789012345;
$f2 =  987654.3210987654;

$s1 = '123456.6789012345';
$s2 = '987654.3210987654';

$p = 10;

$df1 = Decimal::create($f1, $p);
$df2 = Decimal::create($f2, $p);

$dfs1 = Decimal::create((string)$f1, $p);
$dfs2 = Decimal::create((string)$f2, $p);

$ds1 = Decimal::create($s1, $p);
$ds2 = Decimal::create($s2, $p);

var_dump((string)$f1, (string)$s1, (string)$df1, (string)$dfs1, (string)$ds1);
var_dump((string)$f2, (string)$s2, (string)$df2, (string)$dfs2, (string)$ds2);

$rf = $f1 * $f2;
$rdf = $df1->mul($df2);
$rdfs = $dfs1->mul($dfs2);
$rds = $ds1->mul($ds2);

var_dump((string)$rf, (string)$rdf, (string)$rdfs, (string)$rds);
```
as result you'll get
```php
string(15) "123456.67890123"
string(17) "123456.6789012345"
string(15) "123456.67890123"
string(15) "123456.67890123"
string(17) "123456.6789012345"
string(15) "987654.32109877"
string(17) "987654.3210987654"
string(15) "987654.32109877"
string(15) "987654.32109877"
string(17) "987654.3210987654"
string(15) "121932522385.31"
string(23) "121932522385.3031578899"
string(23) "121932522385.3031578899"
string(23) "121932522385.3070344336"
```
As you can see during casting to string you're loosing some precision.

**Comment by ajcastro** [comment]
Yah you're right. I also realized that when I try to var_dump 0.3, it will become 0.2999999...
