### ISSUE TITLE
[Proposal] Add typecasting methods like toFloat(), toInt(), etc.

### ISSUE THREAD

**Issue by ajcastro** [rtlopez/decimal#3]
![image](https://cloud.githubusercontent.com/assets/4918318/23647478/fcd0e1a0-0350-11e7-88d7-141da8862e08.png)

**Comment by rtlopez** [comment]
Can you provide me some examples where you may need conversion to float? This looks strange, because you are using a specialized decimal library to keep precision and then you are loosing it by converting to float. 

From my experience I used it in two contexts:
1. orm - which mostly for decimal fields accepts string values
2. views - where I passed original decimal objects and displayed them using specialized helpers for formatting.

and never needed to use a float casting.

To convert to integer you can use the ->truncate() or ->round() which depends on context you are calling it. It is done intentionally to induce some reflection.

**Comment by ajcastro** [comment]
Yes you're right. It's not really good to cast it back to float since you will lose precision. I just realized and experienced it lately.
